---
title: "Gganimate para a Carol"
description: |
  Exemplo de um gganimate para a Carol.
author:
  - name: Athos Petri Damiani
    url: https://github.com/athospd
date: 09-06-2021
preview: image/thumbnail.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


## dados fake

```{r}
library(tidyverse)
library(gganimate)


# base fake ----------------------------------
base <- bind_rows(
  beaver1 %>% mutate(ocorrencia = "novas internações", day = if_else(day == 346, 307, 308)),
  beaver2 %>% mutate(ocorrencia = "novas mortes")
) %>%
  filter(day == 307) %>%
  mutate(
    data = as.Date(time, origin = "2015-01-01"),
    ocorrencia = factor(ocorrencia)
  ) %>%
  dplyr::select(
    data, ocorrencia, total_por_dia = temp
  )

versao_da_base_10_05 <- base %>% mutate(versao_da_base = "Versão da base: 10/05", total_por_dia = ifelse(data > "2021-01-01", total_por_dia * 1, total_por_dia))
versao_da_base_17_05 <- base %>% mutate(versao_da_base = "Versão da base: 17/05", total_por_dia = ifelse(data > "2021-01-01", total_por_dia * 1.01, total_por_dia))
versao_da_base_24_05 <- base %>% mutate(versao_da_base = "Versão da base: 24/05", total_por_dia = ifelse(data > "2021-01-01", total_por_dia * 1.03, total_por_dia))
versao_da_base_31_05 <- base %>% mutate(versao_da_base = "Versão da base: 31/05", total_por_dia = ifelse(data > "2021-01-01", total_por_dia * 1.06, total_por_dia))

base_com_todas_as_versoes <- bind_rows(
  versao_da_base_10_05,
  versao_da_base_17_05,
  versao_da_base_24_05,
  versao_da_base_31_05
)

glimpse(base_com_todas_as_versoes)
```

## ggplot e gganimate


```{r}
# grafico ------------------------------------
gif <- base_com_todas_as_versoes %>%
  ggplot() +
  geom_line(aes(x = data, y = total_por_dia, colour = ocorrencia), size = 2) +
  geom_text(aes(label = versao_da_base), x = as.Date("2020-01-01"), y = 40, size = 6) +
  geom_vline(
    colour = "gray80", 
    size = 1, 
    xintercept = max(base_com_todas_as_versoes$data)
  ) +
  geom_text(
    colour = "gray50", 
    size = 4, 
    fontface = "bold",
    x = max(base_com_todas_as_versoes$data), 
    y = min(base_com_todas_as_versoes$total_por_dia), 
    hjust = -0.05, 
    label = format(max(base_com_todas_as_versoes$data), "%d/%m")
  ) +
  theme_minimal(15) +
  labs(
    x = "data", 
    y = "Total por dia", 
    colour = NULL, 
    title = "Internações por SRAG e mortes confirmadas por Covid-19",
    subtitle = "Média móvel por data de ocorrência do Estado de SP",
    caption = "Fonte: Sivep-Gripe (Ministério da Saúde)"
  ) +
  scale_x_date(date_labels = "%b %Y") +
  theme(
    legend.position = "top"
  ) +
  transition_states(versao_da_base, transition_length = 2, wrap = TRUE, state_length = 2)


animate(gif, width = 650, height = 480)
```


## salvar

```{r, eval = FALSE}
gganimate::save_animation(gganimate::last_animation(), file = "sivep_gripe.gif")
```

